// This file is auto-generated by Supabase
// Do not edit directly

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      games: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          title: string
          status: string
          // Add other game fields as needed
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          title: string
          status?: string
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          title?: string
          status?: string
        }
      }
      participants: {
        Row: {
          id: string
          game_id: string
          name: string
          created_at: string
        }
        Insert: {
          id?: string
          game_id: string
          name: string
          created_at?: string
        }
        Update: {
          id?: string
          game_id?: string
          name?: string
          created_at?: string
        }
      }
      // Add other tables as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
